#!/bin/sh /etc/rc.common

START=90
USE_PROCD=1
NAME=starfail

start_service() {
    procd_open_instance
    procd_set_param command /usr/sbin/starfaild
    procd_set_param respawn 5000 3 0
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

stop_service() {
    procd_kill starfaild
}

reload_service() {
    ubus call starfail reload 2>/dev/null || true
}

service_triggers() {
    procd_add_reload_trigger "starfail"
}
