name: Autonomous Copilot Manager

on:
  # Trigger when PRs are created, updated, or marked ready
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]

  # Trigger when workflow runs require approval or finish
  workflow_run:
    workflows: ["*"]
    types: [requested, completed]

jobs:
  approve-and-merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      actions: write

    steps:
      - name: Approve Pending Workflow Runs
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          echo "🔄 Checking for workflow runs that need approval..."
          RUNS=$(gh run list --json databaseId,status,headBranch --jq '.[] | select(.status=="waiting") | .databaseId')
          for RUN_ID in $RUNS; do
            echo "✅ Approving workflow run $RUN_ID"
            gh api --method POST repos/${{ github.repository }}/actions/runs/$RUN_ID/approve
          done

      - name: Approve Pull Request (Self-Review)
        if: github.event_name == 'pull_request'
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          echo "✅ Approving PR #${{ github.event.number }}"
          gh pr review ${{ github.event.number }} --approve

      - name: Merge PR Automatically (If Checks Pass)
        if: github.event_name == 'pull_request'
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          echo "✅ Attempting to merge PR #${{ github.event.number }}"
          gh pr merge ${{ github.event.number }} --auto --merge
