name: Autonomous Copilot Manager

on:
  schedule:
    - cron: "*/10 * * * *" # Check every 10 minutes
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]
  workflow_run:
    workflows: ["*"]
    types: [requested, completed]

jobs:
  autonomous-manager:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      actions: write

    steps:
      - name: Install gh CLI
        run: sudo apt-get install gh -y

      - name: Mark Drafts Ready If Copilot Finished
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          echo "🔍 Checking draft PRs..."
          PRS=$(gh pr list --state open --json number,isDraft,headRefName --jq '.[] | select(.isDraft==true) | .number')
          for PR in $PRS; do
            echo "Checking PR #$PR"
            LAST_COMMIT=$(gh pr view $PR --json commits --jq '.commits[-1].committedDate')
            MINUTES=$(( ( $(date +%s) - $(date -d "$LAST_COMMIT" +%s) ) / 60 ))
            echo "⏳ Last commit was $MINUTES minutes ago"
            if [ $MINUTES -ge 30 ]; then
              echo "✅ Marking PR #$PR ready for review"
              gh pr ready $PR
            fi
          done

      - name: Approve Pending Workflow Runs
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          RUNS=$(gh run list --json databaseId,status --jq '.[] | select(.status=="waiting") | .databaseId')
          for RUN_ID in $RUNS; do
            echo "✅ Approving workflow run $RUN_ID"
            gh api --method POST repos/${{ github.repository }}/actions/runs/$RUN_ID/approve
          done

      - name: Approve PR (Self-Review)
        if: github.event_name == 'pull_request'
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          echo "✅ Approving PR #${{ github.event.number }}"
          gh pr review ${{ github.event.number }} --approve

      - name: Merge PR Automatically
        if: github.event_name == 'pull_request'
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          echo "✅ Merging PR #${{ github.event.number }}"
          gh pr merge ${{ github.event.number }} --auto --merge
