name: Autonomous Copilot Manager

on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]
  workflow_run:
    workflows: ["*"]
    types: [requested, completed]

jobs:
  approve-and-merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      actions: write
    steps:
      - name: Approve Workflow Runs Automatically
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          RUNS=$(gh run list --branch "$GITHUB_HEAD_REF" --json databaseId,status --jq '.[] | select(.status=="waiting") | .databaseId')
          for RUN_ID in $RUNS; do
            echo "Approving workflow run $RUN_ID"
            gh api --method POST \
              repos/${{ github.repository }}/actions/runs/$RUN_ID/approve
          done

      - name: Approve PR (Self-Review)
        if: github.event_name == 'pull_request'
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          gh pr review $PR_NUMBER --approve

      - name: Merge PR Automatically
        if: github.event_name == 'pull_request'
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          gh pr merge $PR_NUMBER --auto --merge
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
