name: Go Build & Test

on:
  push:
    branches: [ '*' ]
    paths:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
  pull_request:
    branches: [ '*' ]
    paths:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'

permissions:
  contents: read
  pull-requests: read

jobs:
  test:
    runs-on: ubuntu-latest
    name: Go Build & Test
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
          cache: true
      
      - name: Verify dependencies
        run: go mod verify
      
      - name: Download dependencies
        run: go mod download
      
      - name: Run tests
        run: go test -v -race -coverprofile=coverage.out ./...
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.out
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
      
      - name: Build binaries
        run: |
          echo "Building starfaild..."
          go build -o bin/starfaild ./cmd/starfaild
          echo "Building starfailsysmgmt..."
          go build -o bin/starfailsysmgmt ./cmd/starfailsysmgmt
          echo "✅ All binaries built successfully"
      
      - name: Run static analysis
        run: |
          echo "Running golangci-lint..."
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2
          golangci-lint run --timeout=5m
      
      - name: Check for security vulnerabilities
        run: |
          echo "Running gosec security scanner..."
          go install github.com/securecodewarrior/gosec/v2/cmd/gosec@latest
          gosec ./...
      
      - name: Run benchmarks
        run: |
          echo "Running benchmarks..."
          go test -bench=. -benchmem ./pkg/...
      
      - name: Check for race conditions
        run: go test -race ./...
      
      - name: Verify go.mod and go.sum
        run: |
          go mod tidy
          if [ -n "$(git status --porcelain)" ]; then
            echo "::error::go.mod or go.sum needs to be updated. Run 'go mod tidy' locally."
            exit 1
          fi
