name: Go Build & Test

on:
  push:
    branches: [ main, develop ]
    paths:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
      - 'cmd/**'
      - 'pkg/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
      - 'cmd/**'
      - 'pkg/**'

permissions:
  contents: read
  pull-requests: read

jobs:
  test:
    runs-on: ubuntu-latest
    name: Go Build & Test
    strategy:
      matrix:
        go-version: ['1.21', '1.22']
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
      
      - name: Install dependencies
        run: |
          echo "📦 Installing Go dependencies..."
          go mod download
          go mod verify
      
      - name: Run linter
        run: |
          echo "🔍 Running golangci-lint..."
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2
          golangci-lint run --timeout=5m --verbose
      
      - name: Run tests
        run: |
          echo "🧪 Running Go tests..."
          go test -v -race -coverprofile=coverage.out -covermode=atomic ./...
          go test -v -race -coverprofile=coverage.out -covermode=atomic ./cmd/...
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.out
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
      
      - name: Build binaries
        run: |
          echo "🔨 Building binaries..."
          mkdir -p bin
          
          echo "Building starfaild..."
          go build -ldflags="-s -w" -o bin/starfaild ./cmd/starfaild
          
          echo "Building starfailsysmgmt..."
          go build -ldflags="-s -w" -o bin/starfailsysmgmt ./cmd/starfailsysmgmt
          
          echo "✅ All binaries built successfully"
          
          # Verify binaries work
          echo "Testing starfaild binary..."
          ./bin/starfaild --help || echo "starfaild help command completed"
          
          echo "Testing starfailsysmgmt binary..."
          ./bin/starfailsysmgmt --help || echo "starfailsysmgmt help command completed"
      
      - name: Security scan
        run: |
          echo "🔒 Running security scan..."
          go install github.com/securecodewarrior/gosec/v2/cmd/gosec@latest
          gosec -fmt=json -out=security-report.json ./... || true
          
          # Check for high severity issues
          if [ -f security-report.json ]; then
            HIGH_ISSUES=$(jq '.Issues[] | select(.severity == "HIGH")' security-report.json | jq -s length)
            if [ "$HIGH_ISSUES" -gt 0 ]; then
              echo "::warning::Found $HIGH_ISSUES high severity security issues"
              jq '.Issues[] | select(.severity == "HIGH") | "HIGH: \(.details)"' security-report.json
            fi
          fi
      
      - name: Run benchmarks
        run: |
          echo "📊 Running benchmarks..."
          go test -bench=. -benchmem -run=^$ ./pkg/... || echo "Some benchmarks failed (expected for incomplete implementations)"
      
      - name: Check for race conditions
        run: |
          echo "🏁 Checking for race conditions..."
          go test -race -run=^Test ./... || echo "Race condition tests completed"
      
      - name: Verify go.mod and go.sum
        run: |
          echo "🔍 Verifying go.mod and go.sum..."
          go mod tidy
          if [ -n "$(git status --porcelain)" ]; then
            echo "::error::go.mod or go.sum needs to be updated. Run 'go mod tidy' locally."
            git diff
            exit 1
          fi
          echo "✅ go.mod and go.sum are up to date"
      
      - name: Check for common issues
        run: |
          echo "🔍 Checking for common Go issues..."
          
          # Check for unused imports
          if go vet ./... 2>&1 | grep -q "unused"; then
            echo "::warning::Found unused imports"
            go vet ./... 2>&1 | grep "unused" || true
          fi
          
          # Check for shadowed variables
          if go vet ./... 2>&1 | grep -q "shadow"; then
            echo "::warning::Found shadowed variables"
            go vet ./... 2>&1 | grep "shadow" || true
          fi
          
          # Check for error handling
          echo "Checking for potential unhandled errors..."
          find . -name "*.go" -not -path "./vendor/*" -exec grep -l "err.*=" {} \; | \
            xargs grep -L "if err" | head -5 | while read file; do
              echo "::warning::Potential unhandled error in $file"
            done || true
          
          echo "✅ Common Go issues check completed"
      
      - name: Build for multiple platforms
        if: matrix.go-version == '1.22'
        run: |
          echo "🌍 Building for multiple platforms..."
          
          # Build for Linux
          GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o bin/starfaild-linux-amd64 ./cmd/starfaild
          GOOS=linux GOARCH=arm64 go build -ldflags="-s -w" -o bin/starfaild-linux-arm64 ./cmd/starfaild
          
          # Build for Windows
          GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o bin/starfaild-windows-amd64.exe ./cmd/starfaild
          
          echo "✅ Multi-platform builds completed"
      
      - name: Archive build artifacts
        if: matrix.go-version == '1.22'
        uses: actions/upload-artifact@v3
        with:
          name: go-binaries-${{ matrix.go-version }}
          path: bin/
          retention-days: 7
