name: Security Scan

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    name: Security Scan
    steps:
    - uses: actions/checkout@v4
    
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'
        
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'
        
    - name: Check for hardcoded secrets
      run: |
        echo "Checking for potential hardcoded secrets..."
        if grep -r -n -i "password\|secret\|token\|key" --include="*.sh" --include="*.md" --include="*.json" . | grep -v "YOUR_" | grep -v "PLACEHOLDER" | grep -v "example"; then
          echo "::warning::Found potential hardcoded secrets"
        fi
