name: Security Scan

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  security-scan:
    runs-on: ubuntu-latest
    name: Security Scan
    steps:
    - uses: actions/checkout@v4
    
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'
        
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always() && github.event_name != 'pull_request'
      continue-on-error: true
      with:
        sarif_file: 'trivy-results.sarif'
        
    - name: Display scan results
      if: always()
      run: |
        echo "Security scan completed. Results:"
        if [ -f "trivy-results.sarif" ]; then
          echo "SARIF file generated successfully"
          # Convert SARIF to human-readable format for PR comments
          if command -v jq >/dev/null 2>&1; then
            echo "Found vulnerabilities:"
            jq -r '.runs[0].results[]?.message.text // "No vulnerabilities found"' trivy-results.sarif | head -10
          fi
        else
          echo "No SARIF file generated"
        fi
        
    - name: Check for hardcoded secrets
      run: |
        echo "Checking for potential hardcoded secrets..."
        if grep -r -n -i "password\|secret\|token\|key" --include="*.sh" --include="*.md" --include="*.json" . | grep -v "YOUR_" | grep -v "PLACEHOLDER" | grep -v "example"; then
          echo "::warning::Found potential hardcoded secrets"
        fi
