name: Shell Script Quality Check

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    name: Shellcheck
    steps:
    - uses: actions/checkout@v4
    
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      with:
        scandir: './Starlink-RUTOS-Failover'
        format: gcc
        severity: error
        
    - name: Check for executable permissions
      run: |
        echo "Checking for executable permissions on shell scripts..."
        find . -name "*.sh" -type f ! -executable -print0 | while IFS= read -r -d '' file; do
          echo "::warning::$file is not executable"
        done
